### ISSUE TITLE
Corregir errores de los enunciados y textos del modo demostrativo

### ISSUE THREAD

**Issue by danrisk** [synergyvision/Riesgo-de-Credito#3]
a continuación te describo los errores observados:

- [x] En el Menú __Datos__, Submenú __Scoring y Rating__, paso1,  la palabra crédito está escrita con  "C" mayúscula al igual que en el paso 6, sin embargo en los pasos 2,4,5,7 y 9, están escritos con minúscula, favor unificar el criterio al escribir esta palabra.

- [x] En el Menú __Scoring y Rating__, Submenú __Estadísticos__ paso 3, revisar palabra "muestra"; en el paso 4 quitar "selecciones de".

- [x] En el Menú __Scoring y Rating__, Submenú __Score de Crédito__ paso 3, revisar texto no esta bien el género, no sé entiende; paso 5 revisar la frase no se entiende.

- [x] En el Menú __Scoring y Rating__, Submenú __Rating de Crédito__ paso1, revisar palabra "mostrado".

- [x] En el Menú __Pérdida por Incumplimiento__, Submenú __Pérdida por Cliente__, paso 6, revisar palabra "obtener".

- [x] En el Menú __Pérdida por Incumplimiento__, Submenú __Pérdida por Clase__, paso 4, revisar palabra "obtener".

- [x] En el Menú __Credit Risk +__, Submenú __Resultados__, paso 5, revisar palabra "exposición".

- [x] En el Menú __Credit Risk +__, Submenú __Stress Testing__, paso 3, revisar palabra "metodología".

- [x] En el Menú __Credimetrics__, Submenú __Simulación y Resultados_, paso 4, revisar palabra "simulación"; paso 6, revisar palabra "clientes".

- [x] En el Menú __Credimetrics__, Submenú __Stress Testing_, paso 3, revisar palabra "metodología".

- [x] En el Menú __Credimetrics__, Submenú __Resultados_, paso 2,3 y 4, revisar y unificar palabra "Backtesting"

**Comment by ArtSynergy** [comment]
Lista la corrección de errores del demo
