### ISSUE TITLE
2da Corrección de textos

### ISSUE THREAD

**Issue by danrisk** [synergyvision/Riesgo-de-Credito#4]
- [x] En el menú __Scoring y Rating__, submenú __Estadísticos__, paso 4, dice "tipo", debería decir "tipos".

- [x]  En el menú __Pérdida por Incumplimiento__, submenú __Pérdida por Cliente__, paso 6, cambiar la redacción, hay redundancia de la palabra "confianza".

- [x] En el menú __Pérdida por Incumplimiento__, submenú __Pérdida por Clase__, paso 4, cambiar la redacción, hay redundancia de la palabra "confianza".

- [x] En el menú __Credit Risk +__, submenú __Resultados__, paso 1, dice "credito" y debería decir "crédito".

- [x] En el menú __Backtesting__, submenú __Resultados__, paso 3, revirar palabra "representación".

**Comment by ArtSynergy** [comment]
Listo corrección de errores parte 2
